name: deploy to s3 bucket
on: push
jobs:
  Deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: configure aws
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Code Static code to s3
        run: |
          aws s3 sync ./ s3://aws-git-action-shantaveer/ \
          --exclude "*" \
          --include "index.html"
      
  
